config/routes.rb
Rails.application.routes.draw do
  resources :principalgroupes

  resources :sousgroupes

  resources :agences

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/principalgroupe.rb
class Principalgroupe < ActiveRecord::Base
  has_many :sousgroupes
end

app/controllers/principalgroupes_controller.rb
class PrincipalgroupesController < ApplicationController
  before_action :set_principalgroupe, only: [:show, :edit, :update, :destroy]

  # GET /principalgroupes
  # GET /principalgroupes.json
  def index
    @principalgroupes = Principalgroupe.all
  end

  # GET /principalgroupes/1
  # GET /principalgroupes/1.json
  def show
  end

  # GET /principalgroupes/new
  def new
    @principalgroupe = Principalgroupe.new
  end

  # GET /principalgroupes/1/edit
  def edit
  end

  # POST /principalgroupes
  # POST /principalgroupes.json
  def create
    @principalgroupe = Principalgroupe.new(principalgroupe_params)

    respond_to do |format|
      if @principalgroupe.save
        format.html { redirect_to @principalgroupe, notice: 'Principalgroupe was successfully created.' }
        format.json { render :show, status: :created, location: @principalgroupe }
      else
        format.html { render :new }
        format.json { render json: @principalgroupe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /principalgroupes/1
  # PATCH/PUT /principalgroupes/1.json
  def update
    respond_to do |format|
      if @principalgroupe.update(principalgroupe_params)
        format.html { redirect_to @principalgroupe, notice: 'Principalgroupe was successfully updated.' }
        format.json { render :show, status: :ok, location: @principalgroupe }
      else
        format.html { render :edit }
        format.json { render json: @principalgroupe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /principalgroupes/1
  # DELETE /principalgroupes/1.json
  def destroy
    @principalgroupe.destroy
    respond_to do |format|
      format.html { redirect_to principalgroupes_url, notice: 'Principalgroupe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_principalgroupe
      @principalgroupe = Principalgroupe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def principalgroupe_params
      params.require(:principalgroupe).permit(:name)
    end
end

app/helpers/principalgroupes_helper.rb
module PrincipalgroupesHelper
end

app/views/principalgroupes/_form.html.erb
<%= form_for @principalgroupe, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  principalgroupes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/principalgroupes/edit.html.erb
<%- model_class = Principalgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Principalgroupe %></h1>
</div>
<%= render :partial => 'form' %>

app/views/principalgroupes/index.html.erb
<%- model_class = Principalgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => Principalgroupe %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @principalgroupes.each do |principalgroupe| %>
      <tr>
        <td><%= principalgroupe.id %></td>
        <td><%= principalgroupe.name %></td>
        <td><%=l principalgroupe.created_at, format: :long %></td>
        <td>
          <%= link_to principalgroupe_path(principalgroupe), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to principalgroupe_path(principalgroupe), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_principalgroupe_path,
            :class => 'btn btn-primary' %>

app/views/principalgroupes/new.html.erb
<%- model_class = Principalgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Principalgroupe %></h1>
</div>
<%= render :partial => 'form' %>

app/views/principalgroupes/show.html.erb
<%- model_class = Principalgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => Principalgroupe %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @principalgroupe.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              principalgroupes_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_principalgroupe_path(@principalgroupe), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              principalgroupe_path(@principalgroupe),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>