config/routes.rb
Rails.application.routes.draw do
  resources :principalgroupes

  resources :sousgroupes

  resources :agences

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/agence.rb
class Agence < ActiveRecord::Base
  belongs_to :principalgroupe
  belongs_to :sousgroupe
end

app/controllers/agences_controller.rb
class AgencesController < ApplicationController
  before_action :set_agence, only: [:show, :edit, :update, :destroy]

  # GET /agences
  # GET /agences.json
  def index
    @agences = Agence.all
  end

  # GET /agences/1
  # GET /agences/1.json
  def show
  end

  # GET /agences/new
  def new
    @agence = Agence.new
  end

  # GET /agences/1/edit
  def edit
  end

  # POST /agences
  # POST /agences.json
  def create
    @agence = Agence.new(agence_params)

    respond_to do |format|
      if @agence.save
        format.html { redirect_to @agence, notice: 'Agence was successfully created.' }
        format.json { render :show, status: :created, location: @agence }
      else
        format.html { render :new }
        format.json { render json: @agence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agences/1
  # PATCH/PUT /agences/1.json
  def update
    respond_to do |format|
      if @agence.update(agence_params)
        format.html { redirect_to @agence, notice: 'Agence was successfully updated.' }
        format.json { render :show, status: :ok, location: @agence }
      else
        format.html { render :edit }
        format.json { render json: @agence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agences/1
  # DELETE /agences/1.json
  def destroy
    @agence.destroy
    respond_to do |format|
      format.html { redirect_to agences_url, notice: 'Agence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agence
      @agence = Agence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agence_params
      params.require(:agence).permit(:name, :principalgroupe_id, :sousgroupe_id)
    end
end

app/helpers/agences_helper.rb
module AgencesHelper
end

app/views/agences/_form.html.erb
<%= form_for @agence, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  agences_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/agences/edit.html.erb
<%- model_class = Agence -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Agence %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agences/index.html.erb
<%- model_class = Agence -%>
<div class="page-header">
  <h1><%=t '.title', :default => Agence %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @agences.each do |agence| %>
      <tr>
        <td><%= agence.id %></td>
        <td><%= agence.name %></td>
        <td><%=l agence.created_at, format: :long %></td>
        <td>
          <%= link_to agence_path(agence), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to agence_path(agence), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_agence_path,
            :class => 'btn btn-primary' %>

app/views/agences/new.html.erb
<%- model_class = Agence -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Agence %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agences/show.html.erb
<%- model_class = Agence -%>
<div class="page-header">
  <h1><%=t '.title', :default => Agence %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @agence.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              agences_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_agence_path(@agence), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              agence_path(@agence),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>